services:
  # Service for the Vite Development Server
  app:
    image: my-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/bin/sh", "-c", "npm run dev-and-test"]
    ports:
      - "5173:5173"
      - "51204:51204"

    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: {}
